version: "3"

networks:
  nginx-php-mysql:

services:

  #nginx
  nginx-service:
    image: nginx:stable-alpine
    container_name: nginx-container
    ports:
      - "8989:80"
    volumes:
      - ./app:/var/www/project
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - nginx-php-mysql
    depends_on:
      - php-service
      - mysql-service

  #php
  php-service:
    build:
      context: .
      dockerfile: ./php/Dockerfile
    container_name: php-container
    ports:
      - "9000:9000"
    volumes:
      - ./app/:/var/www/project
    networks:
      - nginx-php-mysql

  #mysql
  mysql-service:
    image: mysql:8
    container_name: mysql-container
    ports:
      - "4306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=hola
      - MYSQL_PASSWORD=hola
      - MYSQL_USER=user
    networks:
      - nginx-php-mysql

  #node
  node-service:
    image: node:latest
    container_name: node-container
    working_dir: /var/www/project
    volumes:
      - ./app/:/var/www/project
    networks:
      - nginx-php-mysql