#index:
#    path: /
#    controller: App\Controller\DefaultController::index

app_lucky_number:
  path: /sandbox/number
  controller: App\Controller\Sandbox\SandboxController::number

app_autowire_test:
  path: /sandbox/autowire
  controller: App\Controller\Sandbox\SandboxController::autowireTest

app_create_dimension_auto:
  path: /dimension/create_auto/{name}/{weight}
  controller: App\Controller\Dimension\DimensionController::createAuto
  methods: GET
  defaults:
    name: 'default_name'
    weight: 0
  requirements:
    name: '[a-zA-Z]+'
    weight: '\d+'

app_create_dimension:
  path: /dimension/create
  controller: App\Controller\Dimension\DimensionController::create
  methods: GET

app_save_dimension:
  path: /dimension/save
  controller: App\Controller\Dimension\DimensionController::save
  methods: POST

app_edit_dimension:
  path: /dimension/edit/{identity}
  controller: App\Controller\Dimension\DimensionController::edit
  methods: GET
  requirements:
    name: '[a-zA-Z0-9\-]+'