#index:
#    path: /
#    controller: App\Controller\DefaultController::index

app_lucky_number:
  path: /dimension/number
  controller: App\Controller\Dimension\DimensionController::number

app_create_dimension:
  path: /dimension/create
  controller: App\Controller\Dimension\DimensionController::create
