#index:
#    path: /
#    controller: App\Controller\DefaultController::index

app_lucky_number:
  path: /sandbox/number
  controller: App\Controller\Sandbox\SandboxController::number

app_autowire_test:
  path: /sandbox/autowire
  controller: App\Controller\Sandbox\SandboxController::autowireTest

app_create_dimension:
  path: /dimension/create/{name}/{weight}
  controller: App\Controller\Dimension\DimensionController::create
  methods: GET
  defaults:
    name: 'default_name'
    weight: 0
  requirements:
    name: '[a-zA-Z]+'
    weight: '\d+'
