services:

  #APPLICATION PRESENTERS
  App\Infrastructure\Presenters\Application\Dimension\CreateDimensionPresenter: ~
  App\Application\Dimension\CreateDimensionPresenter: '@App\Infrastructure\Presenters\Application\Dimension\CreateDimensionPresenter'

  App\Infrastructure\Presenters\Application\Dimension\GetDimension\GetDimensionPresenter: ~
  App\Application\Dimension\GetDimension\GetDimensionPresenter: '@App\Infrastructure\Presenters\Application\Dimension\GetDimension\GetDimensionPresenter'

  #DOMAIN PRESENTERS
  App\Infrastructure\Presenters\Domain\Dimension\DimensionPresenter: ~
  App\Domain\Dimension\DimensionPresenter: '@App\Infrastructure\Presenters\Domain\Dimension\DimensionPresenter'